services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://0.0.0.0:2380
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/etcd-data
    networks:
      easy-chat:

  redis:
    image: redis:alpine3.18
    ports:
      - "16379:6379"
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:
    command: redis-server --requirepass easy-chat --appendonly yes

  mysql:
    image: mysql:8.0
    ports:
      - "23306:3306"
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: easy-chat
    restart: always
    networks:
      easy-chat:

  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: easy-chat
    ports:
      - "47017:27017"
    volumes:
      - ./components/mongo/data:/data/db
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      easy-chat:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ws2ms_chat:8:1,ms2ps_chat:8:1,msg_to_mongo:8:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    depends_on:
      - zookeeper
    networks:
      easy-chat:

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    restart: always
    depends_on:
      - etcd
    volumes:
      - ./components/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      easy-chat:

  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.2.0-debian}
    container_name: apisix
    restart: always
    user: "0:0"
    depends_on:
      - etcd
      - apisix-dashboard
    volumes:
      - ./components/apisix/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./components/apisix/logs:/usr/local/apisix/logs
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9093:9092/tcp"
    networks:
      easy-chat:
  jeager:
    image: jaegertracing/all-in-one:latest
    container_name: jeager
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: always
    networks:
      easy-chat:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=easy-chat
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - JVM_XMS=512m
      - JVM_XMX=512m
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./components/nacos/logs:/home/nacos/logs
      - ./components/nacos/data:/home/nacos/data
    depends_on:
      - mysql
    restart: always
    networks:
      easy-chat:
  # sail:
  #   image: ccr.ccs.tencentyun.com/hyy-yu/sail:latest
  #   container_name: sail
  #   ports:
  #     - "8108:8108"
  #   volumes:
  #     - "./components/sail/compose-cfg.toml:/app/cfg.toml"
  #   restart: always
  #   # platform: linux/amd64  # 镜像只有 ARM64 版本，移除平台限制让其通过模拟器运行
  #   networks:
  #     easy-chat:
  elasticsearch:
    image: elasticsearch:7.17.4
    user: "1000:1000"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    container_name: elasticsearch
    restart: always
    environment:
      - 'cluster.name=elasticsearch'
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'xpack.security.enabled=false'
    networks:
      easy-chat:

#  kibana:
#    image: kibana:7.17.4
#    container_name: kibana
#    restart: always
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./components/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
#    ports:
#      - '5601:5601'
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
#    networks:
#      easy-chat:

  logstash:
    image: logstash:7.17.4
    container_name: logstash
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/logstash/logs:/usr/share/logstash/logs
      - ./components/mysql/data/ad16009c6861-slow.log:/var/logs/mysql-slow.log
      - ./components/apisix/logs:/var/logs/apisix
      - ./components/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - '5044:5044'
      - '50000:50000/tcp'
      - '50000:50000/udp'
      - '9600:9600'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      easy-chat:
networks:
  easy-chat:
    driver: bridge